### ISSUE TITLE
没有功能实现？

### ISSUE THREAD

**Issue by shenshouer** [Devifish/aliyun-ddns#1]
咋就写了一个壳，没有实际功能实现呢？

**Comment by devifish** [comment]
> 咋就写了一个壳，没有实际功能实现呢？

疫情完后加班太累，  回来只想躺

**Comment by shenshouer** [comment]
我也一样的，下班到家就晚上11点多了。
不过我基于你的实现了一部分，目前还有些bug，我这边调试完了推个pr吧

**Comment by shenshouer** [comment]
https://github.com/Devifish/aliyun-ddns/pull/2
